version: '3.3'
services:
  couchdb:
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK}
      - default
  proxy:
    networks:
      - ${TRAEFIK_PUBLIC_NETWORK}
      - default

networks:
  traefik-public:
    external:
      name: traefik-public
