version: '3.3'
services:
   backend:
      container_name: backend
      hostname: backend
      build:
         args: 
            env: dev
         context: ./wwapi
         dockerfile: Dockerfile
      command: 'bash -c "sleep 10 && wwapi init && /start-reload.sh"'
      depends_on: 
         - couchdb
      env_file:
         - env-couch.env
         - env-backend.env
      environment:
         - SERVER_HOST=http://${DOMAIN}
         - SERVER_NAME=${DOMAIN}
      ports:
         - 80:8080
      volumes:
         - ./wwapi/wwapi:/app/wwapi
   couchdb:
      container_name: couchdb
      hostname: couchdb
      build:
         context: ./
         dockerfile: Dockerfile
      env_file:
         - env-couch.env
      ports:
         - 5984:5984
      image: couchdb:latest
      volumes:
         - ./volumes/db/local.ini:/opt/couchdb/etc/local.ini