version: '3.3'
services:
   backend:
      container_name: backend
      hostname: backend
      build:
         args: 
            env: dev
         context: ./wordweaver
         dockerfile: Dockerfile
      command: 'bash -c "wordweaver validate-data && wordweaver init && /start-reload.sh"'
      env_file:
         - env-backend.env
      environment:
         - SERVER_HOST=http://${DOMAIN}
         - SERVER_NAME=${DOMAIN}
      ports:
         - 80:8080
      volumes:
         - ./wordweaver/wordweaver:/app/wordweaver