version: '3.3'
services:
  db:
    env_file:
      - env-couch.env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
  web:
    env_file:
      - env-couch.env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
      - WWLANG=moh
