services:
   backend-tests:
      build:
         context: ./wordweaver
         dockerfile: tests.dockerfile
      command: bash -c "while true; do sleep 1; done"
         - backend
      env_file:
         - env-backend.env
      environment:
         - SERVER_NAME=backend
      volumes:
         - ./wordweaver/wordweaver:/app/wordweaver