version: '3.3'
services:
  couchdb:
    deploy:
      labels:
        - traefik.frontend.rule=Host:db.${DOMAIN}
        - traefik.enable=true
        - traefik.port=5984
        - traefik.tags=${TRAEFIK_PUBLIC_TAG}
        - traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
  proxy:
    deploy:
      labels:
        # For the configured domain
        - traefik.frontend.rule=Host:${DOMAIN}
        # For a domain with and without 'www'
        # Comment the previous line above and un-comment the line below
        # - "traefik.frontend.rule=Host:www.${DOMAIN},${DOMAIN}"
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=${TRAEFIK_PUBLIC_TAG}
        - traefik.docker.network=${TRAEFIK_PUBLIC_NETWORK}
        - traefik.frontend.entryPoints=http,https
        - traefik.frontend.redirect.entryPoint=https
        # Uncomment the config line below to detect and redirect www to non-www (or the contrary)
        # The lines above for traefik.frontend.rule are needed too
        # - "traefik.frontend.redirect.regex=^https?://(www.)?(${DOMAIN})/(.*)"
        # To redirect from non-www to www un-comment the line below
        # - "traefik.frontend.redirect.replacement=https://www.${DOMAIN}/$$3"
        # To redirect from www to non-www un-comment the line below
        # - "traefik.frontend.redirect.replacement=https://${DOMAIN}/$$3"
  backend:
    deploy:
      labels:
        - traefik.frontend.rule=PathPrefix:/api,/docs,/redoc,/openapi.json
        - traefik.enable=true
        - traefik.port=80
        - traefik.tags=${TRAEFIK_TAG}
