version: '3.3'
services:
  couchdb:
    env_file:
      - env-couch.env
  backend:
    env_file:
      - env-couch.env
      - env-backend.env
    environment:
      - SERVER_NAME=${DOMAIN}
      - SERVER_HOST=https://${DOMAIN}
