version: '3.3'
services:
   backend:
      build:
         args: 
            env: dev
         context: ./wordweaver
         dockerfile: Dockerfile
      command: 'bash -c "wordweaver validate-data && wordweaver init && /start-reload.sh"'
      env_file:
         - env-backend.env
      environment:
         - SERVER_HOST=http://backend
         - SERVER_NAME=backend
      expose:
         - 8080
      networks:
         - web
      volumes:
         - ./wordweaver/wordweaver:/app/wordweaver
   certbot:
      image: certbot/certbot
      volumes:
         - ./volumes/ssl/certbot/conf:/etc/letsencrypt
         - ./volumes/ssl/certbot/www:/var/www/certbot
         - ./volumes/ssl/certbot/logs:/var/log/letsencrypt
      networks:
         - web
      entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
   reverse:
      command: /bin/bash -c "envsubst '$$SERVER_NAME' < /etc/nginx/conf.d/wordweaver.template > /etc/nginx/conf.d/default.conf && /bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
      environment:
         - SERVER_NAME=${DOMAIN}
      restart: always
      image: nginx:latest
      networks:
         - web
      ports: 
         - 80:80
         - 443:443
      volumes:
         - ./volumes/reverse/nginx/conf/wordweaver.template:/etc/nginx/conf.d/wordweaver.template
         - ./volumes/ssl/certbot/conf:/etc/letsencrypt
         - ./volumes/ssl/certbot/www:/var/www/certbot
networks:
   web:
      external: true