version: '3.3'
services:
  backend-tests:
    build:
      context: ./wwapi
      dockerfile: tests.dockerfile
    command: bash -c "while true; do sleep 1; done"
    env_file:
      - env-couch.env
      - env-backend.env
    environment:
      - SERVER_NAME=backend
    depends_on: 
      - couchdb
      - backend
