version: '3.3'
services:
  proxy:
    command: --docker \
      --docker.swarmmode \
      --docker.watch \
      --docker.exposedbydefault=false \
      --constraints=tag==${TRAEFIK_TAG} \
      --logLevel=INFO \
      --accessLog \
      --web
    web:
      command: 'bash -c "wwapi init && uvicorn --reload --host 0.0.0.0 --port 5200 --log-level info wwapi.main:app"'
