version: '3'
restart: always
services:
    start_dependencies:
        image: dadarek/wait-for-dependencies
        depends_on:
          - db
        command: db:5984
    db:        
        image: roedoejet/wordweaver-db
        ports:
            - "5984:5984"
        environment:
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: password
    web:
        image: roedoejet/wordweaver
        command: 'bash -c "wwapi init && uvicorn --reload --host 0.0.0.0 --port 5200 --log-level info wwapi.main:app"'
        ports:
            - "5200:$PORT"
        depends_on:
            - start_dependencies
        environment:
            COUCHDB_USER: admin
            COUCHDB_PASSWORD: password
            WWLANG: moh
        